/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeatureBox {
        "img": string;
    }
    interface FeatureContent {
    }
    interface FeatureMain {
    }
    interface FeatureSidebar {
        "handleActive": (event: CustomEvent) => Promise<void>;
        "sidebarTitle": string;
    }
    interface SidebarToggle {
    }
}
declare global {
    interface HTMLFeatureBoxElement extends Components.FeatureBox, HTMLStencilElement {
    }
    var HTMLFeatureBoxElement: {
        prototype: HTMLFeatureBoxElement;
        new (): HTMLFeatureBoxElement;
    };
    interface HTMLFeatureContentElement extends Components.FeatureContent, HTMLStencilElement {
    }
    var HTMLFeatureContentElement: {
        prototype: HTMLFeatureContentElement;
        new (): HTMLFeatureContentElement;
    };
    interface HTMLFeatureMainElement extends Components.FeatureMain, HTMLStencilElement {
    }
    var HTMLFeatureMainElement: {
        prototype: HTMLFeatureMainElement;
        new (): HTMLFeatureMainElement;
    };
    interface HTMLFeatureSidebarElement extends Components.FeatureSidebar, HTMLStencilElement {
    }
    var HTMLFeatureSidebarElement: {
        prototype: HTMLFeatureSidebarElement;
        new (): HTMLFeatureSidebarElement;
    };
    interface HTMLSidebarToggleElement extends Components.SidebarToggle, HTMLStencilElement {
    }
    var HTMLSidebarToggleElement: {
        prototype: HTMLSidebarToggleElement;
        new (): HTMLSidebarToggleElement;
    };
    interface HTMLElementTagNameMap {
        "feature-box": HTMLFeatureBoxElement;
        "feature-content": HTMLFeatureContentElement;
        "feature-main": HTMLFeatureMainElement;
        "feature-sidebar": HTMLFeatureSidebarElement;
        "sidebar-toggle": HTMLSidebarToggleElement;
    }
}
declare namespace LocalJSX {
    interface FeatureBox {
        "img"?: string;
    }
    interface FeatureContent {
    }
    interface FeatureMain {
    }
    interface FeatureSidebar {
        "onScActiveState"?: (event: CustomEvent<any>) => void;
        "sidebarTitle"?: string;
    }
    interface SidebarToggle {
        "onStSetActiveSidebar"?: (event: CustomEvent<boolean>) => void;
        "onStSetToggleElement"?: (event: CustomEvent<HTMLElement>) => void;
    }
    interface IntrinsicElements {
        "feature-box": FeatureBox;
        "feature-content": FeatureContent;
        "feature-main": FeatureMain;
        "feature-sidebar": FeatureSidebar;
        "sidebar-toggle": SidebarToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "feature-box": LocalJSX.FeatureBox & JSXBase.HTMLAttributes<HTMLFeatureBoxElement>;
            "feature-content": LocalJSX.FeatureContent & JSXBase.HTMLAttributes<HTMLFeatureContentElement>;
            "feature-main": LocalJSX.FeatureMain & JSXBase.HTMLAttributes<HTMLFeatureMainElement>;
            "feature-sidebar": LocalJSX.FeatureSidebar & JSXBase.HTMLAttributes<HTMLFeatureSidebarElement>;
            "sidebar-toggle": LocalJSX.SidebarToggle & JSXBase.HTMLAttributes<HTMLSidebarToggleElement>;
        }
    }
}
