/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FeatureSidebar {
        "handleActive": (event: CustomEvent) => Promise<void>;
        "title": string;
    }
    interface SidebarToggle {
    }
}
declare global {
    interface HTMLFeatureSidebarElement extends Components.FeatureSidebar, HTMLStencilElement {
    }
    var HTMLFeatureSidebarElement: {
        prototype: HTMLFeatureSidebarElement;
        new (): HTMLFeatureSidebarElement;
    };
    interface HTMLSidebarToggleElement extends Components.SidebarToggle, HTMLStencilElement {
    }
    var HTMLSidebarToggleElement: {
        prototype: HTMLSidebarToggleElement;
        new (): HTMLSidebarToggleElement;
    };
    interface HTMLElementTagNameMap {
        "feature-sidebar": HTMLFeatureSidebarElement;
        "sidebar-toggle": HTMLSidebarToggleElement;
    }
}
declare namespace LocalJSX {
    interface FeatureSidebar {
        "onScActiveState"?: (event: CustomEvent<any>) => void;
        "title"?: string;
    }
    interface SidebarToggle {
        "onStSetActiveSidebar"?: (event: CustomEvent<boolean>) => void;
        "onStSetToggleElement"?: (event: CustomEvent<HTMLElement>) => void;
    }
    interface IntrinsicElements {
        "feature-sidebar": FeatureSidebar;
        "sidebar-toggle": SidebarToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "feature-sidebar": LocalJSX.FeatureSidebar & JSXBase.HTMLAttributes<HTMLFeatureSidebarElement>;
            "sidebar-toggle": LocalJSX.SidebarToggle & JSXBase.HTMLAttributes<HTMLSidebarToggleElement>;
        }
    }
}
